### ISSUE TITLE
Making a data request not working

### ISSUE THREAD

**Issue by chynamyerz** [saltastroops/data-archive-backend#75]
When making a data request, an error is thrown.

The error message is: Response not successful: Received status code 400

**Comment by hettlage** [comment]
This is a frontend issue. Moving it there.

**Comment by hettlage** [comment]
Ah, it isn't a frontend issue. There was just a very similar frontend issue...

**Comment by hettlage** [comment]
Not really a bug - probably some files were missing. But an error should be raised in this case.
