### ISSUE TITLE
Use better names for data request files

### ISSUE THREAD

**Issue by hettlage** [saltastroops/data-archive-backend#82]
The data request files currently have a name like data_request_18.zip. It might be better to use a timestamp ("data_request_2020-02-01_12:45:35.zip", using the current time).

**Comment by chynamyerz** [comment]
The file name is formed on the frontend.

I will close this issue here and open it on the frontend

**Comment by chynamyerz** [comment]
Having a filename like this 

filename = `${moment().format("Y-MM-DD_HH:mm:ss")}.zip`;

The ":" between HH, mm and ss get converted to "_"m have any idea why?
